Update catalogue item to use manufacturer id #102
ral-facilities/inventory-management-system-api pull request #115
Opened 2023-11-06 16:55 UTC by MatteoGuarnaccia5

## Description
Changed catalogue items to use manufacturer IDs instead of a manufacturer object. Implemented error checking to ensure manufacturer ID entered in post and patch requests is valid and exists in the database. Updated all unit and e2e tests so that they use manufacturer ID and pass

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
closes #102

2023-11-08 16:36 UTC, VKTB requested changes
Looks good, just a few minor comments. In addition to these, there is also the `test_delete_manufacturer_that_is_a_part_of_catalogue_item` in `e2e\test_manufacturer.py` that needs to be enabled now.

2023-11-08 16:36 UTC, VKTB commented on test/e2e/test_catalogue_item.py
>  def test_partial_update_catalogue_item_change_manufacturer(test_client):
```suggestion
def test_partial_update_catalogue_item_change_manufacturer_id(test_client):
```

2023-11-08 16:36 UTC, VKTB commented on inventory_management_system_api/models/catalogue_item.py
> +    manufacturer_id: str
Its type should be `CustomObjectIdField`. Could you please also update the repo unit tests accordingly?
```suggestion
    manufacturer_id: CustomObjectIdField
```

2023-11-08 16:36 UTC, VKTB commented on test/unit/services/test_catalogue_item.py
We should also test:
- creating a catalogue item with a non-existent manufacturer ID.
- changing/updating the manufacturer ID of a catalogue ID to an existent as well as a non-existent ID.

2023-11-08 16:36 UTC, VKTB commented on test/e2e/test_catalogue_item.py
>      # pylint: disable=fixme
```suggestion
```

2023-11-08 16:36 UTC, VKTB commented on test/e2e/test_catalogue_item.py
>      # pylint: disable=fixme
```suggestion
```

2023-11-08 16:36 UTC, VKTB commented on test/e2e/test_catalogue_item.py
>      # pylint: disable=fixme
```suggestion
```

2023-11-15 10:27 UTC, VKTB commented on inventory_management_system_api/schemas/catalogue_item.py
>      # TODO - Change from manufacturer to manufacturer id
@MatteoGuarnaccia5 This has not been fully addressed as `# pylint: disable=fixme` is still there.

2023-11-15 10:27 UTC, VKTB commented on inventory_management_system_api/models/catalogue_item.py
> +    manufacturer_id: str
@MatteoGuarnaccia5 There are some repo unit tests that have not been updated to return the `manufacturer_id` as `CustomObjectId` object. Have a look at the `test_update` test and some of the `test_list_...` tests.

2023-11-15 11:00 UTC, VKTB requested changes
Just a few more minor stuff I noticed in your recent changes. Like I highlighted in my previous review, could you please enable the `test_delete_manufacturer_that_is_a_part_of_catalogue_item` in `e2e\test_manufacturer.py`?

2023-11-15 16:20 UTC, VKTB commented on test/unit/services/test_catalogue_item.py
> +            manufacturer_id=catalogue_item.manufacturer_id,
If updating it to a different `manufacturer_id` then the catalogue item coming from the database should have a different `manufacturer_id` to the one in the updated `catalogue_item`.
```suggestion
            manufacturer_id=str(ObjectId()),
```

2023-11-15 16:23 UTC, VKTB submitted a review, later dismissed

2023-11-27 17:54 UTC, VKTB commented on test/e2e/test_catalogue_item.py
> +    """/v1/manufacturers
```suggestion
    """
```

2023-11-27 17:54 UTC, VKTB commented on test/e2e/test_manufacturer.py
> +}
```suggestion
    catalogue_item_post = {
        "name": "Catalogue Item A",
        "catalogue_category_id": catalogue_category_id,
        "description": "This is Catalogue Item A",
        "cost_gbp": 129.99,
        "days_to_replace": 2.0,
        "drawing_link": "https://drawing-link.com/",
        "item_model_number": "abc123",
        "is_obsolete": False,
        "properties": [
            {"name": "Property A", "value": 20},
            {"name": "Property B", "value": False},
            {"name": "Property C", "value": "20x15x10"},
        ],
        "manufacturer_id": manufacturer_id
    }
```

2023-12-01 13:03 UTC, joelvdavies approved these changes
LGTM - To be merged with https://github.com/ral-facilities/inventory-management-system/pull/144

2023-12-13 14:55 UTC, VKTB approved these changes
LGTM. I fixed the formatting and did a minor refactor in the tests.

2023-12-13 16:32 UTC, merged