Rename catalogue_item_properties to properties #293
ral-facilities/inventory-management-system-api pull request #294
Opened 2024-06-14 15:06 UTC by joelvdavies

## Description
Renames
- catalogue_item_properties -> properties
- catalogue_item_property -> property
- CatalogueItemProperty -> CategoryProperty (In theory current Property could be ItemProperty following the same scheme)

Where necessary have replaced the resulting `property` variable name with either `property_in` for database models, or `category_property` for schemas.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
Closes #293

2024-06-17 12:16 UTC, VKTB reviewed
> Could we also simplify some schema names by removing the Request in them? The method type already implies its a request to me. In fact in the front end we don't even have the schema e.g. CatalogueItemPostRequestSchema could be CatalogueItemPost which is imported from schemas.

Possibly but we need to make sure that there are no conflicts. It would be an issue if we end up with conflicting class names and having to import this in the same module.

Some initial questions below

2024-06-17 12:16 UTC, VKTB commented on inventory_management_system_api/core/exceptions.py
> +    A mandatory property is missing when a catalogue item is attempted to be created.
I think this one is also raised when an item is attempted to be created so should we update the docstring to mention item?

2024-06-17 12:16 UTC, VKTB commented on inventory_management_system_api/models/catalogue_category.py
> +class CategoryPropertyBase(BaseModel):
Same question - Just `Category` or should it be `CatalogueCategory`?

2024-06-17 12:16 UTC, VKTB commented on inventory_management_system_api/models/catalogue_item.py
I think what we can do here instead is rename these to `CatalogueItemPropertyIn` and `CatalogueItemPropertyOut` and then in `/models/item.py`, we define `ItemPropertyIn` and `ItemPropertyOut` that inherit from these two. This way we have classes for each one. Let me know your thoughts.

2024-06-17 12:50 UTC, joelvdavies commented on inventory_management_system_api/core/exceptions.py
> +class DuplicateCategoryPropertyNameError(Exception):
Yeah wasn't sure either, I think I will just go with CatalogueCategory to be clear.

2024-06-17 12:51 UTC, joshuadkitenge reviewed
Works well with the front end

2024-06-17 12:54 UTC, joelvdavies commented on inventory_management_system_api/core/exceptions.py
> +class DuplicateCategoryPropertyNameError(Exception):
Although looking at it again, we also have `LeafCategoryError`, and DuplicateCatalogueCategoryPropertyNameError is quite long, do you prefer one over the other?

2024-06-17 13:04 UTC, joelvdavies commented on inventory_management_system_api/models/catalogue_item.py
I like that in principle, if we do this here, we should also do the same for schemas. In that case there is also a potential issue where we have generic functions that apply for both, then they would be taking in the base class type which implies its CatalogueItem related when in fact Item ones will work too. Although I guess we could also make it explicit with CatalogueItem | Item.

2024-06-17 13:12 UTC, joelvdavies commented
> Possibly but we need to make sure that there are no conflicts. It would be an issue if we end up with conflicting class names and having to import this in the same module.
> 
Yeah good point, having Schema would resolve that part. I know this also effects some things Joshua is doing on the front end, as there Schema is now being used for form schemas whereas the api schemas are just in a types file without any mention of schema. I think its worth coordinating between us but its a post mvp thing.

2024-06-17 14:27 UTC, VKTB commented on inventory_management_system_api/models/catalogue_item.py
As discussed, we should leave this for the time being.

2024-06-17 14:27 UTC, joelvdavies commented on inventory_management_system_api/models/catalogue_item.py
We discussed and decided to ignore for now as it creates other potential issues when implementing.

2024-06-17 14:44 UTC, joelvdavies commented
@VKTB I had a look at the other service's, I think the use of properties don't need renaming as they are specific to the entity involved e.g. CatalogueCategoryService only deals with catalogue category properties. So I think it was just the property service that needed the renaming as it deals with all of them unless you spot anything else.

2024-06-18 11:32 UTC, VKTB requested changes

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/routers/v1/catalogue_category.py
> +    property_id: str = Path(description="The ID of the property patch"),
```suggestion
    property_id: str = Path(description="The ID of the property to patch"),
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category.py
> +        Adds the unit values to the  based on the provided unit IDs.
```suggestion
        Adds the unit values to the properties based on the provided unit IDs.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category.py
> +        :param properties: List of  to which unit values will be added.
```suggestion
        :param properties: List of properties to which unit values will be added.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category.py
> +        :return: List of  with unit values added.
```suggestion
        :return: List of properties with unit values added.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category.py
> +        logger.info("Adding unit values to the ")
```suggestion
        logger.info("Adding unit values to the properties")
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category_property.py
> +        category_property: CategoryPropertyPatchRequestSchema,
```suggestion
        catalogue_category_property: CategoryPropertyPatchRequestSchema,
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_category_property.py
> +        :param property: The property values to update
```suggestion
        :param catalogue_category_property: The property values to update
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/routers/v1/catalogue_category.py
> +    category_property: CategoryPropertyPostRequestSchema,
```suggestion
    catalogue_category_property: CategoryPropertyPostRequestSchema,
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/routers/v1/catalogue_category.py
> +    category_property: CategoryPropertyPatchRequestSchema,
```suggestion
    catalogue_category_property: CategoryPropertyPatchRequestSchema,
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_item.py
> +        is. It then processes the catalogue item properties.
```suggestion
        is. It then processes the properties.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/catalogue_item.py
> +        them.
```suggestion
        `NonLeafCatalogueCategoryError` if it is. If the properties are being updated, it also processes them.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/item.py
> +        be overwritten by the .
```
        be overwritten by the properties.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/utils.py
> +    :param properties: The supplied
```
    Go through a list of properties to check for any duplicate names during creation of a catalogue category or an
    addition of a property later on.

    :param properties: The supplied properties
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/utils.py
> +    filters the matching , adds the property units, and finally validates the property values.
```
    Process and validate supplied properties based on the defined properties. It checks for missing mandatory, filters
    the matching properties, adds the property units, and finally validates the property values.
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/utils.py
> +    _validate_property_values(defined_properties_dict, supplied_properties_dict)
```python
    # Some mandatory properties may not have been supplied
    _check_missing_mandatory_properties(defined_properties_dict, supplied_properties_dict)
    # Some non-mandatory properties may not have been supplied
    supplied_properties_dict = _merge_non_mandatory_properties(defined_properties_dict, supplied_properties_dict)
    # Supplied properties do not have names as we can't trust they would be correct
    _add_property_names(defined_properties_dict, supplied_properties_dict)
    # Supplied properties do not have units as we can't trust they would be correct
    _add_property_units(defined_properties_dict, supplied_properties_dict)
    # The values of the supplied properties may not be of the expected types
    _validate_property_values(defined_properties_dict, supplied_properties_dict)
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/utils.py
> +    return {property.id: property.model_dump() for property in properties}
Shadows the built-in `property` name.
```suggestion
    return {prop.id: prop.model_dump() for prop in properties}
```

2024-06-18 11:32 UTC, VKTB commented on inventory_management_system_api/services/utils.py
> +    :param supplied_properties: The supplied .
```suggestion
    :param supplied_properties: The supplied properties.
```

2024-06-18 11:39 UTC, joelvdavies commented on inventory_management_system_api/routers/v1/catalogue_category.py
> +    logger.debug("Catalogue item property data: %s", category_property)
🤦‍♂️ I forgot to search for that particular case combination

2024-06-18 11:42 UTC, VKTB commented
@joelvdavies A lot of the requested changes are related to `catalogue item property` / `catalogue item properties` being replaced with an empty space instead of `property` / `properties`. This is the case in the tests but I didn't go and suggest changes as it would take me quite some time.

2024-06-18 12:52 UTC, joelvdavies commented
@VKTB Sorry about that, I thought I had only done it to a few files but I didn't realise I had done it everywhere. I have gone through the tests searching for double spaces for ` .` and fixed the rest I found.

2024-06-19 09:01 UTC, joshuadkitenge approved these changes

2024-06-20 08:16 UTC, merged