refactored units e2e tests #334
ral-facilities/inventory-management-system-api pull request #348
Opened 2024-08-01 09:07 UTC by MatteoGuarnaccia5

## Description
Enter a description of the changes here

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
connect to #{issue number}

2024-08-08 08:01 UTC, joelvdavies requested changes
Looks good, just some minor things and recent changes I made in my latest PRs.

2024-08-12 07:55 UTC, joelvdavies requested changes

2024-08-12 07:55 UTC, joelvdavies commented on test/e2e/test_unit.py
> +    _delete_response: Response
```suggestion
    _delete_response_unit: Response
```

2024-08-12 08:05 UTC, joelvdavies commented on test/e2e/test_unit.py
> +        """Test creating a unit with a duplicate name"""
```suggestion
    def test_create_unit_with_duplicate_value(self):
        """Test creating a unit with a duplicate value."""
```

2024-08-12 08:22 UTC, joelvdavies commented
For ease of merging later, could you rebase this branch on top of items in https://github.com/ral-facilities/inventory-management-system-api/pull/359 please.

2024-09-05 14:10 UTC, VKTB reviewed
Just some very minor things, it looks good otherwise.

2024-09-05 14:10 UTC, VKTB commented on test/unit/services/test_unit.py
> +        """
```suggestion
        """Calls the `UnitService` `create` method with the appropriate data from a prior call to `mock_create`."""
```

2024-09-05 14:56 UTC, joelvdavies approved these changes

2024-09-05 14:57 UTC, VKTB approved these changes

2024-09-05 14:57 UTC, merged