Refactor usage status tests #335
ral-facilities/inventory-management-system-api pull request #357
Opened 2024-08-08 10:05 UTC by MatteoGuarnaccia5

## Description

see #335

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
closes #335

2024-08-12 08:17 UTC, joelvdavies requested changes

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +    _post_response: Response
```suggestion
    _post_response_usage_status: Response
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +    _get_response = Response
```suggestion
    _get_response_usage_status: Response
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +    _delete_response: Response
```suggestion
    _delete_response_usage_status: Response
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
>  End-to-End tests for the Usage status router
```suggestion
End-to-End tests for the usage status router
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +        `UsageStatusPostSchema`.
```suggestion
        :param usage_status_post_data: Dictionary containing the usage status data as would be required for a 
                                                            `UsageStatusPostSchema`.
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +        for a `UsageStatusSchema`.
```suggestion
        :param expected_usage_status_get_data: Dictionary containing the expected usage status data as would be required 
                                                                          for a `UsageStatusSchema`.
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +        """Test creating a usage status with a duplicate value"""
```suggestion
    def test_create_usage_status_with_duplicate_value(self):
        """Test creating a usage status with a duplicate value."""
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +        for a `UsageStatusSchema`.
```suggestion
        :param expected_usage_status_get_data: Dictionary containing the expected usage status data as would be required 
                                                                           for a `UsageStatusSchema`.
```

2024-08-12 08:17 UTC, joelvdavies commented on test/e2e/test_usage_status.py
> +    def get_usage_statuss(self) -> None:
```suggestion
    def get_usage_status(self) -> None:
```

2024-08-12 08:17 UTC, joelvdavies commented on test/mock_data.py
> +}
```suggestion

# New

USAGE_STATUS_POST_DATA_NEW = {"value": "New"}

USAGE_STATUS_IN_DATA_NEW = {
    **USAGE_STATUS_POST_DATA_NEW,
    "code": "new",
}

USAGE_STATUS_GET_DATA_NEW = {
    **USAGE_STATUS_POST_DATA_NEW,
    **CREATED_MODIFIED_GET_DATA_EXPECTED,
    "code": "new",
    "id": ANY,
}

# Used

USAGE_STATUS_POST_DATA_USED = {"value": "Used"}

USAGE_STATUS_IN_DATA_USED = {
    **USAGE_STATUS_POST_DATA_USED,
    "code": "used",
}

USAGE_STATUS_GET_DATA_USED = {
    **USAGE_STATUS_POST_DATA_USED,
    **CREATED_MODIFIED_GET_DATA_EXPECTED,
    "code": "used",
    "id": ANY,
}
```

2024-08-12 08:17 UTC, joelvdavies commented on test/unit/repositories/test_usage_status.py
> +        duplicate usage status.
```suggestion
        :param duplicate_usage_status_in_data: Either `None` or a dictionary containing usage status data for a 
                                                                        duplicate usage status.
```

2024-08-12 08:17 UTC, joelvdavies commented on test/unit/repositories/test_usage_status.py
> +    # pylint: disable=duplicate-code
```suggestion
```
We have been putting
```
# Expect some duplicate code inside tests as the tests for the different entities can be very similar
# pylint: disable=duplicate-code
```
at the top of our test files instead. Could you also remove the corresponding enable below.

2024-09-06 11:59 UTC, VKTB requested changes

2024-09-06 11:59 UTC, VKTB commented on test/e2e/test_usage_status.py
> +            "properties": [],
We can probably just use `CATALOGUE_ITEM_DATA_REQUIRED_VALUES_ONLY`?
```suggestion
            **CATALOGUE_ITEM_DATA_REQUIRED_VALUES_ONLY,
```

2024-09-06 11:59 UTC, VKTB commented on test/e2e/test_usage_status.py
> +            "properties": [],
We can probably just use `ITEM_DATA_REQUIRED_VALUES_ONLY`?
```suggestion
            **ITEM_DATA_REQUIRED_VALUES_ONLY,
```

2024-09-06 12:39 UTC, VKTB commented on test/e2e/test_manufacturer.py
> -        assert self._post_response_manufacturer.json()["detail"][0]["msg"] == message
Unused

2024-09-06 12:40 UTC, VKTB commented
@joelvdavies Could you please have a look at the changes I requested and review the code I pushed to address them? I am not sure why codecov is reporting a drop of 22.35% in the coverage..

2024-09-06 13:10 UTC, joelvdavies approved these changes

2024-09-06 13:23 UTC, VKTB approved these changes

2024-09-06 13:23 UTC, merged